# nest server configuration
spring.application.name: 'flock-integration'
spring.profiles.include: 'flock'
server.port: 0
server.ssl.enabled: false

security:
  user.name: 'root'
  user.password: 'change'

asio:
  timeout: 3000
  feature:
    vph-metadata: on
    vph-uri-auth: off
    allow-federation: on

flock.identifier: 'urn:asio:dataset:integration'

logging.level.: 'OFF'  # root logger
logging.level:
  at.ac.univie.isc.asio: 'OFF'
  at.ac.univie.isc.asio.events: 'OFF'
  at.ac.univie.isc.asio.security: 'OFF'
  com.hp.hpl.jena.arq.exec: 'OFF'
  org.d2rq.db.SQLIterator: 'OFF'
  org.springframework.boot.actuate.audit.listener.AuditListener: 'OFF'

spring.security.debug: off
spring.jersey.debug: off
