# ============================== #
# asio sparql node configuration #
# ============================== #

# these settings override default settings in application.yml if ASIO_MODE 'flock' is active
spring.profiles.include: 'flock'

flock.identifier: 'urn:asio:flock'
asio.feature.allow-federation: on

asio.timeout: 60000

server.port: 8080
server.ssl.enabled: false

security.user:  # basic auth credentials for /api
  name: root
  password: change

