# ====================== #
# asio vph configuration #
# ====================== #

# these settings override default settings in application.yml if ASIO_MODE 'vph' is active
spring.profiles.include: 'brood,ajp,mysql'

server.port: 8080
ajp.port: 8009
server.ssl.enabled: false

security.user:  # basic auth credentials for /api
  name: root
  password: change

asio:
  timeout: 30000  # timeout used for actions during request processing, e.g. connecting to DB
  metadata-repository: 'http://vphshare.atosresearch.eu/metadata-extended/rest/'  # atos metadata endpoint

asio.feature: # feature toggles
  vph-metadata: on # fetch metadata from a remote http service (URL set in metadata-repostiory)
  vph-uri-auth: on # enable the URI based authentication mechanism for VPH
  allow-federation: off # enable processing of federated SPARQL queries in local datasets
  global-datasource: off # override local connection settings with global one from asio.jdbc
  multi-tenancy: off # create an isolated user per deployed dataset

asio.d2rq.pool-size: 5  # fixed size of d2rq model pool per deployed dataset
# asio.jdbc:  # provide global jdbc connection settings, required for multi-tenancy support
  # url: 'jdbc:mysql:///'
  # username: 'root'
  # password: 'change'
  # privileges: ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'DROP']
