# core server settings - override only if you know what you are doing
spring.application.name: 'asio'
# spring.pidfile: '/path'
server.session-timeout: 0
server.port: 8443
server.ssl:
  enabled: true
  # this must be provided by deployers
  # key-store: '/path/to/keystore'
  key-store-password: 'asio_keys'
  key-alias: 'asio'
  key-password: 'asio_keys'
  # use DumpSslInfo to find supported ciphers
  # cannot use list notation as backing property is an array
  ciphers: 'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA'

server.servletPath: '/explore'
management.context-path: '/insight'

security:
  user.name: 'root'
  # if not provided by deployer a random UUID is the password
  # user.password: 'password'
  basic.realm: 'asio'
  basic.enabled: false
  ignored: ['/*.html', '/css/**', '/js/**', '/img/**', '/fonts/**', '/snorql/**', '/**/favicon.ico']
  require-ssl: '${server.ssl.enabled:false}'

# asio default settings
asio:
  home: '${defaults.home:${java.io.tmpdir}}'
  timeout: 30000
  metadata-repository: 'http://vphshare.atosresearch.eu/metadata-extended/rest/'
  api:
    delegate-authorization-header: 'Authorization'
    override-accept-parameter: '_type'
    default-media-type: ['application/xml', '*/*;q=0.5']
    default-language: 'en'
    reserved-container-names: ['api', 'explore']
  # override jdbc settings of containers
  # jdbc:

# serialization settings
spring.mvc:
  locale: 'en_UK'
  date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
spring.jackson:
  date-format: 'com.fasterxml.jackson.databind.util.ISO8601DateFormat'
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
  deserialization:
    FAIL_ON_NUMBERS_FOR_ENUMS: true
    ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

# log errors and top level events, but disable some noisy loggers in libraries
logging.level.: 'WARN'
logging.level:
  at.ac.univie.isc.asio.events: 'INFO'
  org.springframework.boot.actuate.audit.listener.AuditListener: 'INFO'
  com.hp.hpl.jena.arq.exec: 'OFF'
  org.d2rq.db.SQLIterator: 'OFF'
